CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    username VARCHAR(30) NOT NULL UNIQUE,
    email VARCHAR(100),
    password VARCHAR(255),
    psw_as_entered VARCHAR(255),
    is_member BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS posts (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    title VARCHAR(255),
    content VARCHAR(255),
    created_at DATE,
    author INTEGER NOT NULL,

    CONSTRAINT fk_posts_author
    FOREIGN KEY (author) REFERENCES users(id) ON DELETE CASCADE
)